schemaVersion: 1
sessionDefaultsProfiles:
  waypoint-writer:
    projectPath: /Users/jrozell/Desktop/personal/PokeStopBuddy/WaypointWriter.xcodeproj
    scheme: WaypointWriter
    configuration: Debug
    simulatorName: WaypointWriter
    simulatorId: 07198D13-CA01-4645-8119-6CE86BA1E94D
    bundleId: com.jacobrozell.waypointwriter
    simulatorPlatform: iOS Simulator
  waypoint-writer-ipad:
    projectPath: /Users/jrozell/Desktop/personal/PokeStopBuddy/WaypointWriter.xcodeproj
    scheme: WaypointWriter
    configuration: Debug
    simulatorName: WaypointWriter iPad
    simulatorId: 9561485E-B69C-42AD-BB9D-938246E3372C
    bundleId: com.jacobrozell.waypointwriter
    simulatorPlatform: iOS Simulator
activeSessionDefaultsProfile: waypoint-writer-ipad
